### ISSUE TITLE
Tighter seLinux policy to insert/remove OOT kernel modules. 

### ISSUE THREAD

**Issue by hershpa** [kubernetes-sigs/kernel-module-management#100]
**Issue Summary:**
We would like to evaluate if it is possible to use a tighter seLinux policy to insert/remove OOT kernel modules. With a finer control seLinux policy, this would eliminate any unnecessary permissions provided by spc_t.

**Issue Detail:**
KMMO uses seLinux option [spc_t](https://danwalsh.livejournal.com/74754.html) (super privileged container type) for Module Loader pod which may be over-privileged to insert/remove the OOT kernel modules. We would like to explore if there is a tighter seLinux policy we can use instead. One particular option we would like to try is the [user-container-selinux](https://github.com/intel/user-container-selinux). Currently, KMMO does not expose any interface to set a custom seLinux policy for the driver container deployed by daemonSet. 

**Suggested Priority (P1-P3) & Urgent (Urgent, medium, Low):**
P1 urgent

**Solution Proposal:**
Is it possible to expose an interface available in module yaml to try this seLinux policy instead of default spc_t? In the meantime, we are in the process of testing whether user-container-selinux policy can be used by directly modifying KMMO.

**Comment by qbarrand** [comment]
Thank you for the write-up. I'm all for moving to a tighter type, but is there a use case for adding that field to the CRD?
If we find a tighter type that allows module loading and unloading, let's have always KMM create DaemonSets with that instead of `spc_t`.
To experiment, we can run debug builds of KMM or even just create standalone pods from YAML with that config.

**Comment by qbarrand** [comment]
Update 2022/11/30: still looking for a tighter policy.

**Comment by mregmi** [comment]
We are currently experimenting with a custom SeLinux policy. This approach consists of:
- Creating a custom SELinux policy (a new label) for KMMO.
- Create a patch for containers/container-selinux with the above policy.
- Merge and make the policy available in next container-selinux package.
- make a change in KMMO code base to use the new custom label.

**Comment by qbarrand** [comment]
Starting in v2.0.0, the SELinux type of the worker container [can be configured](https://kmm.sigs.k8s.io/documentation/configure/#workerselinuxtype) in the operator options. Closing this issue.
