### ISSUE TITLE
ER: Expose Module name as build environment variable

### ISSUE THREAD

**Issue by cdvultur** [kubernetes-sigs/kernel-module-management#103]
I find helpful to have the module name exposed as an environment variable.
This is helpful in the build process where the module name could be needed in the build process. Also will help in case of yaml reuse.

**Comment by qbarrand** [comment]
It would probably use useful to have access to the `Module`'s namespace as well. Those two values should be available both in the `containerImage` field and as build arguments when building in-cluster.

**Comment by qbarrand** [comment]
Rephrasing this issue a bit to make it more clear.
Just like we have `KERNEL_FULL_VERSION` available for substitution [in the `Module`'s `containerImage` field](https://github.com/kubernetes-sigs/kernel-module-management/blob/main/ci/module-kmm-ci-build-sign.yaml#L13) and `KERNEL_VERSION` [available as a build argument](https://github.com/kubernetes-sigs/kernel-module-management/blob/main/ci/kmm-kmod-dockerfile.yaml#L9) when building, it would be useful to also have the `Module`'s name and namespace as new variables.
