### ISSUE TITLE
FirmwarePath extra directory level causing FW initialization issue.

### ISSUE THREAD

**Issue by hershpa** [kubernetes-sigs/kernel-module-management#109]
**Issue Summary:**
FirmwarePath extra directory level is causing FW initialization to fail.

**Suggested Priority(P1-P3) & Urgent(Urgent, medium, Low):**
P1 and Urgent

**Issue Detail:**
We have added `firmware_class.path=/var/lib/firmware` as a kernel parameter using MCO to tell the kernel to look for firmware in /var/lib/firmware since the /lib/firmware is read only on RHCOS. 

KMMO copies the firmware to `/var/lib/firmware/Module.Name/FirmwarePath/`. Due to this extra directory level, FirmwarePath, the FW initialization fails as it cannot find the firmware binaries. When I manually copy the firmware to `/var/lib/firmware/Module.Name/`, then the FW initialization works.

**Solution Proposal:**
Is it possible for KMMO to copy firmware to  `/var/lib/firmware/FirmwarePath/` instead of `/var/lib/firmware/Module.Name/FirmwarePath/`. This removes Module.Name from the path and thus can be customized based on what value the user sets for FirmwarePath. 

One other related question, can the FirmwarePath be referenced as a variable in the dockerfile?

The use case would be user can simply reference FirmwarePath as a variable when they are copying the firmware from builder image. It would be a improvement from a user point of view so that firmware is always in the right place and user does not have to explicitly list path again in dockerfile.

**Comment by hershpa** [comment]
Another question related to this issue, when the path is created for firmware by KMMO (/var/lib/firmware/<Module.Name>), it appends the name of the module (metadata.name). Wouldn't it make more sense for KMMO to use spec.moduleLoader.container.modprobe.moduleName when it creates the firmware path?

**Comment by uMartinXu** [comment]
In the GA release installed from OCP-4.12 operator Hub. This issue is still there.

**Comment by qbarrand** [comment]
Verified today with @hershpa that it is working as expected.
