### ISSUE TITLE
decouple building process from Module CRD/CR

### ISSUE THREAD

**Issue by uMartinXu** [kubernetes-sigs/kernel-module-management#115]
### Issue Summary:
The building process should be decoupled from Module CRD/CR for driver version control feature 
### Suggested Priority(P1-P3) & Urgent(Urgent, medium, Low):
P2 & Medium
### Issue Detail:
Let start from the the roles and players. Normally there are three players and roles in the whole KMMO picture.
1. Cluster Administrators who use KMMO to ( build ) deploy and manage the OOT drivers.
2. Driver developer who develop and release the driver code
3. KMMO developer who develop and maintain the KMMO operator in some K8S platform
Currently, the Driver building process is embedded into Module CR yaml, and this CR yaml file owner should be cluster Administrators. But the driver build process should be maintained by Driver developer, and the building process might change to different version of driver. That is out of the Cluster Administrators' knowledge scope. So to maintain the CR yaml and let it match with each driver version should not be handled by Cluster Administers.  We should find a way to decouple building process from Module CRD/CR, and let the build process can natively match with each driver version.
### Solution Proposal
Let driver developer maintain a building process which can be docker file or scripts for each driver version in the driver project. With the moduleVersion and moduleProjectURL KMMO knows which build process can be used to build the driver container image. So clusterAdminstrators don't need to maintain the build process in the module CRD/CR yaml file anymore

**Comment by qbarrand** [comment]
I think Preflight could be a solution to that problem - it makes KMM behave as if it had seen a node with a new kernel. An administrator using that feature could build images targeting kernel versions that are not currently running in the cluster. WDYT?
@yevgeny-shnaidman does that sound right to you?

**Comment by qbarrand** [comment]
@uMartinXu @hershpa @chaitanya1731 just to confirm that extracting the Dockerfile out into a ConfigMap would make sense? Then the `build` section of the CRD would have a field like `configMapName` that would point to that ConfigMap.

**Comment by enriquebelarte** [comment]
FYI. There's a scheduled kmm technical enablement in a few days which relies heavily on [labs](https://github.com/kubernetes-sigs/kernel-module-management/tree/main/docs/labs).  
This change would break all examples in labs.

**Comment by qbarrand** [comment]
@uMartinXu @hershpa @chaitanya1731 I believe this was implemented in #160. OK to close?
