### ISSUE TITLE
Sanity Checking and Driver State Label support

### ISSUE THREAD

**Issue by uMartinXu** [kubernetes-sigs/kernel-module-management#117]
### Issue Summary:
KMMO needs to set  and maintain the OOT driver statues Machine of each work node and label the nodes and report to K8S cluster properly
### Suggested Priority(P1-P3) & Urgent(Urgent, medium, Low):
P2 & Medium
### Issue Detail:
KMMO in charge of deploying the driver container on the nodes. And the driver module will be insmod into kernel. Possibly the other operations also need to be done to enable the driver on the nodes. It is quite possible that enabling the driver in kernel might has some problems. So KMMO needs check the driver enabling operation result and make sure every steps is executed with the proper result. If KMMO find any issue, it needs to label the nodes properly and report to user.  Even after the driver is enabled without any errors, the sanity check should be executed to check whether the driver is ready to use. For example, a simple checking of the driver interfaces and some statues from sysfs or procfs. After the sanity test, we can set the driver label as READY, if the sanity test failed, the label should be FAIL.
### solution proposal
Each driver should has a label to maintain the OOT driver state machine for the node for example:
intel_dGPU_Driver: None/Available/Ready/Fail
intel_dGPU_Driver on the node: from "None" to "Available" when the driver container image is deployed on the node and the driver enable process is done without any issue.  
intel_dGPU_Driver on the node: from "Available" to "Ready" when the sanity Checking is done and verify the driver is ready otherwise change it to Fail.
intel_dGPU_Driver on the node change to None once the driver container image is removed from the node and the driver has been rmmoded from the kernel.
User should has a way to configure the Sanity Check method and use the proper way to check the readiness of the driver after KMMO enabled the driver on the node. And this checking should driver specific.

**Comment by yevgeny-shnaidman** [comment]
@uMartinXu How KMMO should run the HealthCheck code? It probably means running additional container  with privileges to map a host directories. I personally would prefer to not add that capability to KMMO, since it allows user to use KMMO to run any code that customer wants, which sound very close to what SRO did ( and we want to avoid).
Maybe HealthCheck i can be part of the device plugin code. Than the scenario can look like:
1) KMMO loads the module and label the node with driver label
2) KMMO runs the device plugin
3) device plugin runs basic HealthCheck, reports the device to Kube API and adds additional labels to the node

**Comment by uMartinXu** [comment]
I think the KMMO should do the sanity test, not device plugin. Since KMMO manages driver installing and configure the driver, it should be KMMO to check whether the installed and configured steps are right and the driver is ready.

So as how to run Sanity check. I think the driver container image should contain some code (The static linked binary is best) for KMMO to call to check whether the driver is ready to use after insmod and configure the driver.

So as to security, since the sanity checking code is from driver developer and packaged together with the driver, so it should be take as safe as the driver code, and should be trusted same as driver code.

of course, if the sanity checking code is not be packaged into the driver container image, KMMO can ignore the sanity check. 

If still want enhance the Security, SeLinux can be used, let's run KMMO as some tailed SeLinux policy instead of spc_t polity, we can give more fined security control. See issue #100.
for more detail about Selinux policy usage please see
https://github.com/intel/intel-device-plugins-for-kubernetes/issues/762
https://github.com/intel/user-container-selinux and 
https://github.com/containers/container-selinux

**Comment by yevgeny-shnaidman** [comment]
KMMO manages only drivers installation, it does not manage driver configuration. Once driver is installed ( and it is verified by modprobe status), it is up to the customer to start interacting with the driver, including configuration. Also, since configuration iis customer's code, customer operator is better suited for configuring the exact volume mappings and security configurations needed.

**Comment by uMartinXu** [comment]
@yevgeny-shnaidman I agree the configuration and usage of the driver is the duty of user application. And it is good to verify the modeprobe status. However I am afraid that sanity checking just through modeprobe is not good enough. Could we also let driver developers/distributors package a program in the driver container for KMMO to call the check whether the driver is installed properly? I think that might be convenient and useful for cluster-administrator.

**Comment by qbarrand** [comment]
A lot of kmods out there will create device files on the node's filesystem in `/dev` or `/proc`. Interacting with those files to run some initialization code would mean that we mount additional paths into the Module Loader container in RW mode, which requires more permissions (and potentially a more powerful SELinux context, going against #100). I think the Module Loader should do one thing and do it well: load the kernel module.
It feels that the device plugin should be the component running most of the steps that you describe. It has all the permissions required to communicate with the device, as well as hooks to run custom code each time a pod requests the extended resource.
