### ISSUE TITLE
Publish KMM in operatorhub.io

### ISSUE THREAD

**Issue by fabiendupont** [kubernetes-sigs/kernel-module-management#119]
This would allow partners to publish their own operator on operatorhub.io with community-level support.
Early releases in operatorhub.io would advertise KMM to a broader audience. This could be through additional channels, e.g. sprint channel for end of sprint release.

**Comment by ybettan** [comment]
My understanding is:
* u/s - @erusso7 has added u/s KMM to operatorhub.io - https://github.com/k8s-operatorhub/community-operators/pull/2276
* We agreed to no publish m/s to the community operators until we don't get any requirement for it
* d/s I believe we have it in the Redhat catalog. @cdvultur please keep me honest here.
