### ISSUE TITLE
Separate node selector for build process

### ISSUE THREAD

**Issue by hershpa** [kubernetes-sigs/kernel-module-management#140]
Feature Summary:
Separate node selector for build process.

Suggested Priority(P1-P3) & Urgent(Urgent, medium, Low):
P2 and medium

Feature Detail:
Currently, KMM uses node selector for both build and DaemonSet. It would be nice to have a separate node selector for build process since it is not always required that the build occur on the same node as that selected for the DaemonSet to modprobe the kernel module. This allows flexibility for the build to occur on any other node. 

Solution Proposal:
Provide a separate node selector for build process.

**Comment by qbarrand** [comment]
If the build selector is empty or undefined, let us keep using the global one to remain compatible.

**Comment by ybettan** [comment]
Should we use the same "new selector" for signing? or also add a selector for signing?

If we don't then we still have the same issue of waiting for a "special" node with some HW for signing a module that was already built on another node in case we both build an sign the module.

WDYT?

**Comment by qbarrand** [comment]
In which situations would we need special hardware to sign the files?

**Comment by ybettan** [comment]
In case there is no `signSelector` and the user has specified a sign section in the module (let's say without build). The sign job will only be scheduled on nodes with the selector of the module (aka the nodes that a customer will load his driver too) which I believe is what we are trying to avoid for build jobs in this issue.

**Comment by ybettan** [comment]
Hello @hershpa.

After discussing this issue, we tough about a solution that won't modify the API at this point.

As we understand it, your main requirement, is to not *restrict* the build/sign jobs to the same node as the moduleLoader is going to run, but instead to just run on any available node. Is that correct?

If this is the case, we can just remove the node selector from the build/sign jobs and let k8s do his job and schedule the jobs on the best fitting nodes. The `nodeSelector` of the `ModuleLoader` will remain with no changes.

Will this solution be good enough for your usecase at this point?

**Comment by hershpa** [comment]
Hi @ybettan, 

That is correct and sounds good.

**Comment by ybettan** [comment]
As agreed in the community meeting we will proceed with the following:

We add a new selector for build. Regarding the default value we differentiate between v1 and v2.

v1:
If the build selector is not set, we use the selector from the module to maintain the same behavior that we had until now.

v2:
If the build selector is not set, we do not set any selector for the build job and let k8s make the scheduling.
