### ISSUE TITLE
If a kernel mapping's ContainerImage field is empty, use the top-level value

### ISSUE THREAD

**Issue by qbarrand** [kubernetes-sigs/kernel-module-management#173]
> This is a valid point and I think that we have ourselves a bug here, although we have to test and verify it. The bug being: the `ModuleLoaderContainer.Spec.ContainerImage` field is never used, we only use the `ModuleLoaderContainerSpec.KernelMappings[].ContainerImage` field instead. 
> I suggest we open an issue for this bug, verify it and resolve it in a separate PR. WDYT?

_Originally posted by @mresvanis in https://github.com/kubernetes-sigs/kernel-module-management/pull/156#discussion_r1031208602_

**Comment by qbarrand** [comment]
@yevgeny-shnaidman I believe this was addressed by your recent refactor(s)?

**Comment by yevgeny-shnaidman** [comment]
yes
