### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by tkatila** [kubernetes-sigs/kernel-module-management#181]
It's possible to supply a proxy to build phase via buildArgs (https://docs.gitlab.com/ee/ci/docker/using_kaniko.html#building-an-image-with-kaniko-behind-a-proxy). But that doesn't seem to affect the image pull phase. For example my Dockerfile uses "ubuntu:20.04" as base but the image pull timeouts as the node is running in a proxy enabled/limited network. As a trial I duplicated the build phase Pod and added proxy environment variables to it, then image pull worked fine.

Is there a way to supply proxy details to the image pull phase (or kaniko in general I suppose)?

**Comment by qbarrand** [comment]
@tkatila sorry for the late reply. Do you need those variables to be available to kaniko? If we're only talking about build arguments, you can configure them [in the CRD](https://github.com/kubernetes-sigs/kernel-module-management/blob/main/api/v1beta1/module_types.go#L50).

**Comment by tkatila** [comment]
No worries. Yes for kaniko. For the build phase, the build arguments are fine I think. But this would be before the build phase when kaniko fetches the base images.

**Comment by qbarrand** [comment]
I think we would need to add environment variables support for both the build and the signing jobs. That means a CRD change, although it would be backwards compatible.
