### ISSUE TITLE
Make the firmware path on the node configurable

### ISSUE THREAD

**Issue by qbarrand** [kubernetes-sigs/kernel-module-management#246]
Firmwares are deployed by the ModuleLoader pods into `/var/lib/firmware` on the node. That value is currently a constant and is not configurable.
https://github.com/kubernetes-sigs/kernel-module-management/blob/30dd65c93505ae4029178f773d7a284ec87e38e0/internal/daemonset/daemonset.go#L26
We should consider making that path configurable, either per `Module` or as an operator setting.

**Comment by yevgeny-shnaidman** [comment]
The default paths that are supported by kernel without additional configuration:
- /lib/firmware/updates/UTS_RELEASE/
- /lib/firmware/updates/
- /lib/firmware/UTS_RELEASE/
- /lib/firmware/

**Comment by fabiendupont** [comment]
These default paths are read-only on CoreOS, so they are not an option.
I asked the CoreOS team what could be a good default path and they answered that `/var/lib/modules` was the path the thought enabling by default as an alternative module path. That's why it's been hardcoded. If it becomes a configurable value, it suggest that the default remains `/var/lib/modules`.

**Comment by fabiendupont** [comment]
And you can add only one alternative path to the kernel. The kernel arg takes a string and puts it in a file in /sys that accepts only one line with one path. So, making it configurable per Module doesn't really make sense.

**Comment by tkatila** [comment]
Roger. Do you know of any good ways to do it via kubernetes methods? :)

I stumbled into this while using kmmo with a VM image where changes to the base image are disliked. I eventually set the firmware path via sysfs. Another option would be the kernel commandline but I don't know if I personally have access to it. Not easily at least.

**Comment by qbarrand** [comment]
> Do you know of any good ways to do it via kubernetes methods? :)

No. KMM v2.0 will run its own code on nodes and optionally set that value through sysfs.
