### ISSUE TITLE
[GITHUB] Add link to the documentation and description on the project in the repository

### ISSUE THREAD

**Issue by iranzo** [kubernetes-sigs/kernel-module-management#247]
Other repositories have information like:

![image](https://user-images.githubusercontent.com/312463/212886298-b38ec252-d1df-471b-810c-83602e16a404.png)

We should have the link to the docs: http://kmm.sigs.k8s.io/

And some description: 

`Kernel Module Management optionally builds and runs DriverContainers on Kubernetes clusters.`

**Comment by qbarrand** [comment]
We could do that once https://github.com/kubernetes/org/pull/3791 is approved.
