### ISSUE TITLE
Allow unloading in-tree kernel modules

### ISSUE THREAD

**Issue by fabiendupont** [kubernetes-sigs/kernel-module-management#253]
Kernel module management may be used to replace an in-tree module with an out-of-tree version of the same module. This would require calling `modprobe -r <module_name>`, before calling `modprobe -d <module_path> <module_name>`. This could be configurable per module, with a default to `false`, so that there needs to be an intent to remove the existing module.

**Comment by qbarrand** [comment]
Duplicate of #104. @fabiendupont OK to close?

**Comment by yevgeny-shnaidman** [comment]
probably let's leave this one and close the 104?
