### ISSUE TITLE
Build a subproject site for docs

### ISSUE THREAD

**Issue by qbarrand** [kubernetes-sigs/kernel-module-management#27]
Follow the [standard Kubernetes procedure](https://github.com/kubernetes/community/blob/master/github-management/subproject-site-requests.md) to build a docs site on Netlify.

**Comment by iranzo** [comment]
Which 'sig' should KMM be for covering the:

`Desired domain name. It should follow the pattern of <sub-project>.sigs.k8s.io and match the [request](https://github.com/kubernetes/community/blob/master/github-management/subproject-site-requests.md#requesting-a-subproject-domain) for a subproject domain.` part ?

**Comment by qbarrand** [comment]
KMM is part of SIG Node, but in that very case I think we would go with `kmm.sigs.k8s.io`. WDYT?

**Comment by iranzo** [comment]
lgtm, waiting for feedback from the others and we can start the requests to get it rolling

**Comment by iranzo** [comment]
Using the actual mkdocs setup with netlify: https://main--cute-kitsune-42fdb8.netlify.app/  (it's on my account, disregard domain), if it's fine, we can go with current setup and request the domain to have everything up and running

**Comment by iranzo** [comment]
Related DNS: https://github.com/kubernetes/k8s.io/issues/4471
