### ISSUE TITLE
`kmm.node.kubernetes.io/<module-name>.ready` can be removed by accident in some cases

### ISSUE THREAD

**Issue by ybettan** [kubernetes-sigs/kernel-module-management#315]
We are removing the label in case a pod is in terminating state or deleted but there are some cases in which a pod restarts because it crashed for example. In this case for a short period of time we are going to have 2 pods:

* one in terminating state
*  a new one that has been created an is now in running state.
Once the terminating pod will be deleted, KMM will delete the label because it doesn't differentiate between different pods of the same module.

Steps to reproduce:

1. Create a module
2. Delete the module and directly recreate it (you will now have 2 pods as explained)
3. Wait for the terminating pod to finish and then check the labels
4. The label will be gone although we have a module and a running pod

**Comment by ybettan** [comment]
@yevgeny-shnaidman has suggested one possible solution to check if we have a module in the cluster before deleting the label.

**Comment by ybettan** [comment]
Thoughts @qbarrand @mresvanis ?

**Comment by qbarrand** [comment]
I do not see any good way of solving this before v2, unfortunately.

**Comment by yevgeny-shnaidman** [comment]
@ybettan   actually we can use the key=value option, where value is the pod name (as you suggested). There is an option for set-based selectors, meaning that device-plugin needs to just specify the key without value ( if i understand it correctly).  Please see [](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors)

**Comment by yevgeny-shnaidman** [comment]
[set-based](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors)

**Comment by ybettan** [comment]
I have tried to use the `key=value` label and then use `nodeAffinity` in the devicePlugin daemonset but seems to be useless as we can't label the same node with 2 labels that contains the same `key` but different values.

**Comment by qbarrand** [comment]
How about we check if there is a newer pod for the same `Module` on the node when we remove the label?

**Comment by yevgeny-shnaidman** [comment]
it means adding query for all the pods of the Module.  why do we want to go that way? the way @ybettan  is cleaner, in my opinion

**Comment by qbarrand** [comment]
It merely queries the cache - no request going to the API server. And we can fix this bug without changing the existing label or introducing a new one.

**Comment by yevgeny-shnaidman** [comment]
we are just changing our own internal label. And it seems that the code will be a little bit cleaner
