### ISSUE TITLE
Add support for cross-platform building.

### ISSUE THREAD

**Issue by ybettan** [kubernetes-sigs/kernel-module-management#325]
A user should be able to build a `ModuleLoader` image on a specific arch and run it on other archs.

This is especially required for the hub&spoke topology as a user may build his `ModuleLoader` in a x86 cluster but run in on an ARM cluster.

**Comment by ybettan** [comment]
One possible solution to explore would be to use kaniko to build for a specific arch (regardless of the host) using https://github.com/GoogleContainerTools/kaniko#flag---customplatform.

**Comment by qbarrand** [comment]
The doc for kaniko's `--customPlatform` says:
> This is not virtualization and cannot help to build an architecture not natively supported by the build host. This is used to build i386 on an amd64 Host for example, or arm32 on an arm64 host.

It would not help building a kmod for `amd64` on an `arm64` machine.

**Comment by ybettan** [comment]
Bummer. We need another solution then.

**Comment by GerrySeidman** [comment]
***THIS IS JUST A CURIOSITY, NOT A REAL SCENARIO***

BACKGROUND:  
- This week I was updating the AuriStor CSI Operator Documention.  This Operator leverages KMM when I found in one an edge case of an edge case regarding multiple CPU architectures within a clusters which ended with ```(???)```. I see that this closed issue is about exactly 
- To be clear, NONE of our are customers are using anything other than x86_64/amd64, much less heterogeneous clusters.

You may absolutely keep this issue closed.  As for @ybettan 's "Bummer. We need another solution then".... nah... not worth it

Again, this is just a curiosity.  I have already just updated my operator's docs changing from ```(???)``` to ```is not supported``` for this case :)
