### ISSUE TITLE
ModuleLoader and Necessary User-Land Processes

### ISSUE THREAD

**Issue by GerrySeidman** [kubernetes-sigs/kernel-module-management#461]
**Issue Summary (Updated July 24th, 2023)**

Some vender kernel modules require a supporting user-land process that the kernel module makes upcalls into.
- The vendor version of the user-land process must be in sync with the Kernel Module on each nodes to guarantee API/communication compatibility 
- This user-land process (DevicePlugin) can not be restarted on nodes while user applications are running 
  - For example with a distributed file system, restarting would leave a window where the storage is unavailable to currently running user applications

**Current Behavior**

- A single DaemonSet is used for the DevicePlugin.
- Updating the module with changes to the DevicePlugin triggers an immediate shutdown/restart of the DaemonSet Pods on each node.
- The vendor version is scoped to the ModuleLoader (spec.moduleLoader.container.version).

**Required Behavior (AuriStor)**

- The AuriStor Kernel Module and AuriStor "DevicePlugin" (which launches afsd) on any node must exactly match AuriStor Kernel Module release version
  - The DevicePlugin Daemonset upgrade policy can not be rolling update or the Kernel Module Loader and DevicePlugin versions may skew
- Upon submission KMM Module upgrade, the KMM admission controller should validate that the container image for the upgraded Device Plugin exists (admission controller?)

**Proposed Solution (IGNORE: would not work with KMM 2.0)**

Rather vendor deploying their user-land component as a DevicePlugin, add ModuleLoader capabilities allowing for an alternative entry point command to "sleep infinity".  This command could start any necessary user-land components in the "ModuleLoader" container.  It would be up to the Module Vendor to include any necessary components to execute this command in their container image (in addition to the .ko files).  This command must also never exit (equivalent to "sleep infinity"

This could be configured/implemented in a similar manner to how the 'Pod' capabilities are configured in the Device Plugin, but on the Module Loader's kernelMappings.

    kernelMappings:
    -   regexp: "4.18.0-*"
         command: ...
         resources: ...
         volumeMounts: ...
         env:   ...
         volumes: ...

**Comment by GerrySeidman** [comment]
Since KMM already "does the right thing" for Kernel Module mappings, it is likely that the only reason a user would update their KMM module object would when upgrading vendor driver versions.    For example, that may just involve the user changing he  Module's module.spec.moduleLoader.container.version and module.spec.devicePlugin.container.image fields to achieve such an upgrade

**Proposed Solution (Simpler):**
The KMM 1.1 implementation _**may**_ be sufficient by adding the additional ability to have the DevicePlugin DaemonSet:

1. Have an "infinite" TerminationGracePeriod
2. Have an daemonset.spec.updateStrategy.type: OnDelete

**Comment by qbarrand** [comment]
> Rather vendor deploying their user-land component as a DevicePlugin, add ModuleLoader capabilities allowing for an alternative entry point command to "sleep infinity".

For KMM v2, we are targeting one-shot worker Pods that load or unload kmods. They would be short-lived instead of the current DaemonSets that use hooks and run `sleep infinity`.

**Comment by qbarrand** [comment]
I think it is reasonable to give users better control over the update strategy of the device plugin DaemonSet.
@yevgeny-shnaidman WDYT about adding a field for that in the CRD?

**Comment by yevgeny-shnaidman** [comment]
I am not sure i am for it. DevicePlugin should not be a process that other applications should have a hard dependency on. Its main purpose is device initialization/healthcheck/ scheduling data and run-time resource allocation for scheduled containers. As such it can be brought up/down and it should not affect the running user-land processes. In addition, if we add that field, then customers will need to manually delete the pods, so they should know which daemonset KMM is creating. Once we do that , we cannot change implementation of DevicePlugin
