### ISSUE TITLE
Verify that the OLM bundle upgrades successfully from the previous version of KMM

### ISSUE THREAD

**Issue by qbarrand** [kubernetes-sigs/kernel-module-management#478]
This can be achieved by:

- installing the bundle from the current version;
- building a new bundle for the current PR;
- upgrading the existing installation with the new bundle and see if the new bundle deploys as expected.

This likely belongs to a new workflow.

**Comment by ybettan** [comment]
Do we only wish to check if the bundle upgrade successfully or we also want to validate that the new bundle can reconcile old `Module`s without any error? To validate we didn't break anything?

**Comment by qbarrand** [comment]
Let's start with just a successful operator upgrade. We can then expand to verifying the state of `Modules`.
