### ISSUE TITLE
Remove orphan `NodeModulesConfigs`

### ISSUE THREAD

**Issue by qbarrand** [kubernetes-sigs/kernel-module-management#509]
Delete all `NodeModulesConfig` objects that do not correspond to any node.
Do we want to leverage ownership and Kubernetes garbage collection for this?

**Comment by yevgeny-shnaidman** [comment]
leveraging garbage collection is probably the safest way

**Comment by yevgeny-shnaidman** [comment]
implemented by [543](https://github.com/kubernetes-sigs/kernel-module-management/pull/543)
