### ISSUE TITLE
Docs: add an example of Dockerfile that utilizes link for dependencies on in-tree kmod

### ISSUE THREAD

**Issue by qbarrand** [kubernetes-sigs/kernel-module-management#517]
By linking a symbolic link `/opt/lib/modules/${kernelVersion}/system` targeting `/lib/modules/${kernelVersion}`, we can have `depmod` use in-tree kmods from the build node when figuring out dependencies.
Because we mount the host's `/lib/modules/${kernelVersion}` into the ModuleLoader pod, this link remains valid when we run modprobe.

This flow should be documented in the docs and a working example should be provided.

Initial issue: https://github.com/intel/intel-data-center-gpu-driver-for-openshift/issues/49
Mentioned at the [2023-07-26 community meeting](https://docs.google.com/document/d/1b-wFATh2A0Pm1P3k11lniSeRP4q74rUa1fTvmk_ZdWY/edit#heading=h.3nujzz6y2g98).

**Comment by hershpa** [comment]
Hi Quentin, any update on this request for documentation? Thanks!

**Comment by hershpa** [comment]
@qbarrand, will the documentation be updated to indicate KMM v2.0.1 supports this symbolic linking and how the user can leverage it?
