### ISSUE TITLE
Fix flaky unit tests for `internal/cache`

### ISSUE THREAD

**Issue by qbarrand** [kubernetes-sigs/kernel-module-management#528]
Failed Prow job: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kernel-module-management/525/pull-kernel-module-management-unit-tests/1692058636601266176

Tests for `internal/cache` routinely fail as they look affected by some kind of race condition

/kind failing-test

**Comment by mresvanis** [comment]
It's possible that this issue has the same root cause as this CI error: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kernel-module-management/552/pull-kernel-module-management-unit-tests/1699040964334587904
