### ISSUE TITLE
Preserve build pod and log of successful builds for development and debug purposes

### ISSUE THREAD

**Issue by hershpa** [kubernetes-sigs/kernel-module-management#572]
### **Summary:**
Currently, the build pod is immediately deleted after the driver container build completes successfully. However, it is still useful to have access to the build pod, especially the logs to verify build flow of driver container and viewing warnings etc. This is extremely useful during early development and buildout of dockerfile recipe.

### **Proposal:**
Preserve the build pod logs for development and ease of debugging. We can preserve it for a set time interval (i.e. 1 hour) before garbage collecting the build objects.

* Initially discussed in September 20th 2023 [KMM community meeting
](https://docs.google.com/document/d/1b-wFATh2A0Pm1P3k11lniSeRP4q74rUa1fTvmk_ZdWY/edit#heading=h.4a4vsxe001pe)

**Comment by yevgeny-shnaidman** [comment]
I am not sure about... How are we going to kick of GC when the module has been successfully built and deployed and there are no more events? We will need to either schedule reconciliation in 1 hour even after successful completion of create a entirely new job.  I think that maybe the Makefile should be configured to treat warning as errors, and in that case we can see the logs in the failed pod.

**Comment by hershpa** [comment]
Just a bump to resume discussion on this one.

**Comment by qbarrand** [comment]
> I am not sure about... How are we going to kick of GC when the module has been successfully built and deployed and there are no more events?

In the worst case, this will happen 10 hours after the build is complete. I do not think that it is a big deal to keep those outdated objects for 10 hours if they are garbage collected eventually.
