### ISSUE TITLE
Preflight should clean Build verification resource on deletion

### ISSUE THREAD

**Issue by yevgeny-shnaidman** [kubernetes-sigs/kernel-module-management#61]
in case preflight requires build verification, upon preflight CR deletion, all build jobs (completed or not) should also
be deleted. Since each job is labeled with module name and kernel, this will allow to easily distinguish between module jobs and preflight jobs

**Comment by qbarrand** [comment]
@yevgeny-shnaidman was this implemented in #149? Can we close it?

**Comment by yevgeny-shnaidman** [comment]
not yet, i want to run the preflight test to verify it

**Comment by qbarrand** [comment]
@yevgeny-shnaidman can we close now?
