### ISSUE TITLE
Cannot deploy KMM via kubectl apply -k

### ISSUE THREAD

**Issue by cdvultur** [kubernetes-sigs/kernel-module-management#62]
Try to install KMM using:

`kubectl apply -k https://github.com/kubernetes-sigs/kernel-module-management/config/default`

One of the 2 pods remains in ErrImagePull

```
# kubectl get pods
NAME                                               READY   STATUS         RESTARTS   AGE
kmm-operator-controller-manager-5f856ccf84-z77nt   1/2     ErrImagePull   0          11m
```

Events show operator image gets http/400 while pulling the image from registry:
```
  Normal   Pulled          6m23s                  kubelet            Container image "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0" already present on machine
  Normal   Created         6m23s                  kubelet            Created container kube-rbac-proxy
  Normal   Started         6m23s                  kubelet            Started container kube-rbac-proxy
  Warning  Failed          5m7s (x5 over 6m21s)   kubelet            Error: ImagePullBackOff
  Normal   Pulling         4m54s (x4 over 6m23s)  kubelet            Pulling image "gcr.io/k8s-staging-kmm/kernel-module-management:main"
  Warning  Failed          4m53s (x4 over 6m21s)  kubelet            Failed to pull image "gcr.io/k8s-staging-kmm/kernel-module-management:main": rpc error: code = Unknown desc = Requesting bearer token: invalid status code from registry 400 (Bad Request)
  Warning  Failed          4m53s (x4 over 6m21s)  kubelet            Error: ErrImagePull
  Normal   BackOff         75s (x20 over 6m21s)   kubelet            Back-off pulling image "gcr.io/k8s-staging-kmm/kernel-module-management:main"
```

**Comment by ybettan** [comment]
`gcr.io/k8s-staging-kmm/kernel-module-management:main` image isn't published yet.

As a temporary workaround, the image can be build locally and pushed before used.
```
make docker-build IMG=<custom image>
make docker-push IMG=<custom image>
```

Then, just change the image and the tag [here](https://github.com/kubernetes-sigs/kernel-module-management/blob/25abfb1861243916a56d7ae4090a19f4afb8cc95/config/manager/kustomization.yaml#L15-L16)

**Comment by ybettan** [comment]
Will be solved once https://github.com/kubernetes-sigs/kernel-module-management/issues/31 is done.

**Comment by ybettan** [comment]
Small correction regarding https://github.com/kubernetes-sigs/kernel-module-management/issues/62#issuecomment-1243784593.

After, updating the image in the `kustomization.yaml` file, make sure to deploy the local files (and not the remote one). 

We should use
```
kubectl apply -k config/default
```
instead of 
```
kubectl apply -k https://github.com/kubernetes-sigs/kernel-module-management/config/default
```

**Comment by qbarrand** [comment]
`kubectl apply -k https://github.com/kubernetes-sigs/kernel-module-management/config/default` now installs KMM successfully.
