### ISSUE TITLE
Error message should give a hint that ImageRepoSecret field is missing

### ISSUE THREAD

**Issue by cdvultur** [kubernetes-sigs/kernel-module-management#72]
When an user creates a new CR, that builds new kmod, given that the ImageRepoSecret is optional, the operator fails to build the image and in the logs of the operator an error like below is seen:

`cannot get keychain from the registry auth getter: could not get the service account's pull secrets`

Steps to reproduce:

1. Create a module that builds a driver and omit to specify the ImageRepoSecret field
2. The containerImage should point to quay.io, or a registry that required auth for image push/pull . The container image should not exist 

Expected results:
In case the ImageRepoSecret is missing some reference to secret definition should be logged in the logs.

**Comment by yevgeny-shnaidman** [comment]
Closing this issue. The matter will be handled in the:
https://github.com/kubernetes-sigs/kernel-module-management/issues/78

**Comment by cdvultur** [comment]
As agreed, this will be fixed in #78
